.projen/deps.json, .projen/tasks.json, .projenrc.js, API.md, README.md, package.json, src/account.ts, src/index.ts, src/organization.ts, src/organizational-unit.ts, test/__snapshots__/organization.test.ts.snap, test/hello.test.ts, test/organization.test.ts, yarn.lock
=> feat: basic organizations

API.md, src/index.ts, src/policy.ts
=> feat: add policies

src/organizational-unit.ts
=> fix: no ou.id response on deletion

.projen/deps.json, .projen/tasks.json, .projenrc.js, API.md, package.json, src/account-provider/account-provider.ts, src/account-provider/on-event-handler.lambda.ts, src/account.ts, yarn.lock
=> feat: wire account provider

API.md, src/account.ts, src/organization.ts, src/organizational-unit.ts, src/policy.ts, test/__snapshots__/account.test.ts.snap, test/__snapshots__/organizational-unit.test.ts.snap, test/__snapshots__/policy.test.ts.snap, test/account.test.ts, test/organizational-unit.test.ts, test/policy.test.ts
=> feat: add simple tests

.github/workflows/auto-approve.yml, .projenrc.js, yarn.lock
=> feat: auto approve dependabot

src/account-provider/account-provider.ts, src/account.ts, src/example/example.ts, src/organization-provider/organization-provider.ts, src/organization.ts, src/tag-resource-provider/tag-resource-provider.ts, src/tag-resource.ts, test/__snapshots__/account.test.ts.snap, test/__snapshots__/delegated-administrator.test.ts.snap, test/__snapshots__/policy-attachment.test.ts.snap, test/account.test.ts, test/delegated-administrator.test.ts, test/enable-aws-service-access.test.ts, test/enable-policy-type.test.ts, test/organization.test.ts, test/organizational-unit.test.ts, test/policy-attachment.test.ts, test/policy.test.ts, test/tag-resource.test.ts
=> fix: imports from core module

src/organization-provider/on-event-handler.lambda.ts, test/__snapshots__/account.test.ts.snap, test/__snapshots__/enable-policy-type.test.ts.snap, test/__snapshots__/organization.test.ts.snap, test/__snapshots__/organizational-unit.test.ts.snap, test/organization-provier/on-event-handler.lambda.test.ts
=> fix(tests): ensure that organization creation is idempotent

API.md, src/enable-policy-type.ts, src/organization.ts, test/__snapshots__/enable-policy-type.test.ts.snap, test/organization.test.ts
=> feat: enable policy type

API.md, src/account.ts, src/delegated-administrator.ts, src/enable-policy-type.ts, src/organization.ts, test/__snapshots__/account.test.ts.snap, test/__snapshots__/delegated-administrator.test.ts.snap, test/__snapshots__/enable-policy-type.test.ts.snap, test/__snapshots__/policy-attachment.test.ts.snap, test/account.test.ts
=> feat: delegate admin

README.md
=> chore(docs): explain usage

README.md
=> chore(docs): organizational unit props

README.md
=> chore(docs): getting started

API.md, src/account.ts, src/organization.ts
fix: add missing methods to the interface iaccount
=> fix: add missing methods to the interface iaccount

src/policy.ts, test/__snapshots__/integ.default.test.ts.snap, test/__snapshots__/policy-attachment.test.ts.snap, test/__snapshots__/policy.test.ts.snap
fix: unexpected parameter on delete of the policy
=> fix: unexpected parameter on delete of the policy

README.md
=> chore(docs): tagging resources

src/tag-resource-provider/tag-resource-provider.ts
docs: set proper descriptions and links
Closes #111
=> fix: set proper descriptions and links

README.md, src/account-provider/is-complete-handler.lambda.ts, test/__snapshots__/account.test.ts.snap, test/__snapshots__/delegated-administrator.test.ts.snap, test/__snapshots__/integ.default.test.ts.snap, test/__snapshots__/policy-attachment.test.ts.snap, test/account-provider/is-complete-handler.lambda.test.ts
BREAKING CHANGE: If removal policy is set to destroy, account will we be closed on delete event.
=> feat!: close account

README.md
=> chore(docs): better describe hard dependency on us-east-1

src/organization.ts, test/__snapshots__/integ.default.test.ts.snap
enforce a sequential dependency chain of organization resources which cannot be deployed in parallel
fixes: https://github.com/pepperize/cdk-organizations/issues/447
BREAKING CHANGE: Adds resource dependencies which may conflict with existing manual dependencies resulting in circular dependency errors
=> fix: sequentially chain organization resources

README.md
=> fix: minor typo in the word administrator

API.md, src/account.ts, src/delegated-administrator.ts
=> feat(DelegatedAdministrator): added optional region

src/delegated-administrator.ts, test/__snapshots__/delegated-administrator.test.ts.snap, test/__snapshots__/dependency-chain.test.ts.snap, test/__snapshots__/integ.default.test.ts.snap
Call deregisterDelegatedAdministrator on deletion
Fixes https://github.com/pepperize/cdk-organizations/issues/1442
Closes https://github.com/pepperize/cdk-organizations/pull/1443
=> fix: correct onDelete call

API.md, src/account.ts, src/delegated-administrator.ts
Fixes #1617 
First draft, open to feedback.
=> feat(DelegatedAdministrator): allow setting RetentionPolicy
